// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-pages/Eleva.tsx": () => import("../components/mockups/brand-pages/Eleva.tsx"),
  "./components/mockups/brand-pages/PlacIq.tsx": () => import("../components/mockups/brand-pages/PlacIq.tsx"),
  "./components/mockups/brand-pages/SdpGlobalPay.tsx": () => import("../components/mockups/brand-pages/SdpGlobalPay.tsx")
};
